baseURL = "https://hsp.sh/"
languageCode = "pl-pl"
title = "Hackerspace Pomorze"
copyright = "CC-BY-SA"

theme = "black-sheep"

[params]
description = "Hackerspace to miejsce dla osób, którym po prostu się chce!"

[menu]

  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 15
