baseURL = "https://hsp.sh/"
languageCode = "pl-pl"
title = "Hackerspace Pomorze"

theme = "black-sheep"

[menu]

  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 15